### ISSUE TITLE
 Fix stylelint issues

### ISSUE THREAD

**Issue by fokusferit** [wholesale-design-system/scss#18]
- [ ] Fix stylelint issues (2000+) (use stylefmt to autoformat as much as possible)
- [ ] How can we 'force' people to use the stylelint linting rules ?

**Comment by faboweb** [comment]
I would propose a precommit check with linting for forcing linted code.

**Comment by fokusferit** [comment]
kind of duplicate to #32 so closing this and focusing on the other story. implementing precommit means also fixing stuff.
