### ISSUE TITLE
Create arrow-tip for popovers as a mixin

### ISSUE THREAD

**Issue by schluchter** [wholesale-design-system/scss#28]
There are several components that use an arrow tip to indicate that a floating element is "attached" to another control:
* Date picker
* Time picker
* Week picker
* Dropdown

All these components should use the same implementation, therefore I'd suggest a mixin that works well with the border styles we've introduced to heighten arrow tip contrast on white background.

**Comment by fokusferit** [comment]
Seems done.
If not, scream!
