### ISSUE TITLE
Precommit check for linting

### ISSUE THREAD

**Issue by faboweb** [wholesale-design-system/scss#32]
We aligned on having precommit hooks for tests and linting in place until we have CI ready. In this repo there is no precommit hook in place.

**Comment by fokusferit** [comment]
tasks:
- [ ] Add precommit check for now 
- [ ] Fix stylelint issues (2000+) (use stylefmt to autoformat as much as possible)
- [ ] How can we 'force' people to use the stylelint linting rules ?

**Comment by fragsalat** [comment]
I think the precommit hook isn't needed anymore since the linting can be or is done when the circleci job builds

**Comment by faboweb** [comment]
+1

**Comment by fokusferit** [comment]
circleCI is working so no need for this anymore. I'm closing it.
