### ISSUE TITLE
Integrate one more spacing unit.

### ISSUE THREAD

**Issue by myueksel** [wholesale-design-system/scss#50]
XXL is changed from 4rem to 3rem. Use variable XXXL as 4rem in future.

**Comment by myueksel** [comment]
![space v4](https://user-images.githubusercontent.com/25901307/27470714-8519a8dc-57f5-11e7-96a4-33ddfa2da18d.png)

Invision:
https://zalando.invisionapp.com/d/main/#/console/10454474/240308052/preview

**Comment by fokusferit** [comment]
Looks done.
