### ISSUE TITLE
Added new system color palette (yellow)

### ISSUE THREAD

**Issue by myueksel** [wholesale-design-system/scss#55]
I added a yellow palette to exclude orange from system colors, which are enabled for color schemes in future.

**Comment by schluchter** [comment]
@myueksel Please validate all places where orange was used for correctness.

**Comment by myueksel** [comment]
change the color of all elements where was used "west-side" to "gold".
- Border and shadow of input field (warning state).
![screen shot 2017-07-03 at 16 28 02](https://user-images.githubusercontent.com/25901307/27797087-9e38fa88-600c-11e7-84c8-53c16eb569ec.png)

- Left border and icon color of Notification (warning)
![screen shot 2017-07-03 at 16 29 17](https://user-images.githubusercontent.com/25901307/27797134-c8c40504-600c-11e7-8d68-616fef1dfca6.png)

**Comment by fragsalat** [comment]
Done already
