### ISSUE TITLE
Change value of color variable "madang"

### ISSUE THREAD

**Issue by myueksel** [wholesale-design-system/scss#56]
new hex code for madang: #78EB81

![screen shot 2017-07-03 at 10 40 08](https://user-images.githubusercontent.com/25901307/27785012-841837c0-5fdc-11e7-99b9-a91d8d778914.png)

**Comment by schluchter** [comment]
@myueksel Please change the hex value on GitHub directly

**Comment by myueksel** [comment]
pull request is done
