### ISSUE TITLE
Re-implement checkboxes and radio buttons

### ISSUE THREAD

**Issue by schluchter** [wholesale-design-system/scss#6]

**Comment by fokusferit** [comment]
@schluchter @fragsalat 
is still still an open issue ? looks like we iterate on that already months.

**Comment by schluchter** [comment]
In Firefox, they are still tiny to a degree where they're unusable.
![image](https://user-images.githubusercontent.com/760158/29827444-51e80f5c-8cda-11e7-80f8-3db93788c2c7.png)
#72 is the bug associated with this.
